# Generated by Django 4.2.4 on 2023-09-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='hhh', upload_to='pics'),
            preserve_default=False,
        ),
    ]
